# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.isar.g.dart"
    - "build/**"
    - ".dart_tool/**"
  errors:
    experimental_member_use: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: false
    curly_braces_in_flow_control_structures: false
