import 'package:isar/isar.dart';

// This file is auto-generated by Isar after running the build runner
part 'receipt.g.dart'; 

@collection
class Receipt {
  Id id = Isar.autoIncrement; // Local auto-increment ID for fast offline saving

  String? remoteId;           // Supabase UUID (populated only if synced to the backend later)

  late String merchantName;
  late double totalAmount;
  late DateTime date;
  late String category;

  List<String> rawOcrText = []; // Stores the raw extracted text for debugging or backend parsing

  @Index()
  bool isSynced = false;      // A flag to check which local records need to be synced
}