services:
  apk-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: homelab-apk-server:latest
    container_name: apk-server
    restart: unless-stopped
    ports:
      - "9090:80"
    volumes:
      - /opt/apk-server/apks:/usr/share/nginx/html/apks:ro

